- hosts: kong-api-server
  become: true
  tasks:
  - name: Copy Repo in /opt/collin/kong-service
    copy:
      src: ../../api
      dest: /opt/collin/kong-service/
      owner: root
      group: root
      mode: 0640
  
  - name: Start Kong-Api 
    shell: cd /opt/collin/kong-service/; npm i; nohup npm start &
