- hosts: kong-api-server
  become: true
  tasks:
  - name: Create Repo in /opt/collin/kong-service
    copy:
      src: /opt/collin/kong-service/
      dest: /opt/collin/kong-service/

  - name: Install dependencies
    npm: 
      path: /opt/collin/kong-service
  
  - name: Start Kong-Api 
    shell: cd /opt/collin/kong-service; nohup npm start &
